window.SPECTRUM_REGISTRY = [
  {
    id: "jp",
    title_zh: "日本政治・社会価値観スペクトラム診断",
    title_en: "Japan Political Spectrum Test",
    region: "Japan",
    href: "/private-homepage/jp-spectrum/",
    status: "available",
    question_count: 100,
    axis_count: 10,
    languages: ["中文"],
    summary: "面向日本政治现状的 10 维度测试，覆盖福利、财政、安保、外交、外国人、社会、能源、地方与公民自由。",
  },
  {
    id: "us",
    title_zh: "美国政治・社会价值观光谱测试",
    title_en: "United States Political Spectrum Test",
    region: "United States",
    href: "/private-homepage/us-spectrum/",
    status: "available",
    question_count: 160,
    axis_count: 10,
    languages: ["中文", "English"],
    summary: "中英双语美国版，覆盖经济、国家能力、自由秩序、文化、移民、种族、制度、外交、军事与气候。",
  },
  {
    id: "global",
    title_zh: "全球意识形态测试",
    title_en: "Global Ideology Test",
    region: "Global",
    href: "#future",
    status: "planned",
    question_count: null,
    axis_count: null,
    languages: ["中文", "English"],
    summary: "预留：跨国家比较的意识形态坐标，不绑定具体选举或党派。",
  },
  {
    id: "europe",
    title_zh: "欧洲政治光谱测试",
    title_en: "Europe Political Spectrum Test",
    region: "Europe",
    href: "#future",
    status: "planned",
    question_count: null,
    axis_count: null,
    languages: ["中文", "English"],
    summary: "预留：福利国家、欧盟统合、民族国家、移民、气候与外交安全。",
  },
  {
    id: "korea",
    title_zh: "韩国政治光谱测试",
    title_en: "Korea Political Spectrum Test",
    region: "Korea",
    href: "#future",
    status: "planned",
    question_count: null,
    axis_count: null,
    languages: ["中文"],
    summary: "预留：南北关系、财阀改革、劳工、性别、住房、外交安保与世代政治。",
  },
  {
    id: "taiwan",
    title_zh: "台湾政治光谱测试",
    title_en: "Taiwan Political Spectrum Test",
    region: "Taiwan",
    href: "#future",
    status: "planned",
    question_count: null,
    axis_count: null,
    languages: ["中文"],
    summary: "预留：统独/身份、两岸安全、能源、社会政策、劳工与制度改革。",
  },
];
